# services:
#     hwi_oauth.user.provider.entity:
#         class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
#     ib_user.oauth_user_provider:
#         class: IB\StoreBundle\Auth\OAuthProvider
#         arguments: [@session, @service_container]
